### ISSUE TITLE
Keep going

### ISSUE THREAD

**Issue by techasit14607** [ppnplus/thaitube-in-th_extwebsite#1]
You can do it. I believe in you. Support ThaiTube.

**Comment by ppnplus** [comment]
Thank you so much! We will keep improving our website and policies.

ขอบคุณมาก ๆ เลยครับ เราจะพัฒนาเว็บไซต์และปรับปรุงนโยบายต่าง ๆ ของทางเว็บไซต์ต่อไปครับ
